### ISSUE TITLE
Connectivity of a hierarchical mesh

### ISSUE THREAD

**Issue by didadidadada** [rafavzqz/geopdes#10]
Dear Rafa
I am writing to ask if you could help me with how to get the elemental connectivity matrix of a hierarchical mesh?
Best Regards
didadidadada

**Comment by rafavzqz** [comment]
Hi didadidadada,
you can get the connectivity easily making use of the matrix Csub. I write below a few lines of code that compute it. I will probably add a function to compute the connectivity in the next version of the code.

Best,
Rafa

connectivity = zeros (1, hmsh.nel);
shifting_index = cumsum ([0 hmsh.nel_per_level]);

for lev = 1:hmsh.nlevels
  [\~,funs] = sp_get_basis_functions (hspace.space_of_level(lev), hmsh.mesh_of_level(lev),hmsh.active{lev});
  for iel = 1:hmsh.nel_per_level(lev)
    el_number = iel+shifting_index(lev);
    [\~,inds{el_number}] = find (hspace.Csub{lev}(funs{iel},:));
  end
end
inds = cellfun (@unique, inds, 'UniformOutput', false);
nsh_el = cellfun (@numel, inds);

for iel = 1:hmsh.nel
  connectivity(1:nsh_el(iel),iel) = inds{iel};
end

**Comment by didadidadada** [comment]
Dear Rafa
Thank you for your help and generous instructions.

Best,
didadidadada
