### ISSUE TITLE
Error estimation

### ISSUE THREAD

**Issue by hamidratri** [rafavzqz/geopdes#12]
Dear Rafa
Two different posteriori error indicators have been introduced in your paper entitled "Algorithms for the implementation of adaptive isogeometric methods using hierarchical splines" for the scalar field. Are these indicators applicable to the vector field approximations like elasticity problems?
I mean without the exact solution at hand, can we estimate the residual error for the vector field using the above-mentioned error estimators?

**Comment by rafavzqz** [comment]
Dear Hamid,
analogous error estimators should be valid for linear elasticity, but they must be suitably modified for this equation. For instance, for the element-based error indicator for Poisson equation is
h_Q (\int_Q (f + \Delta u)^2)^{1/2} = h_Q (\int_Q (f + \Delta u) \cdot (f + \Delta u))^{1/2}
where \cdot is the scalar product. The analogous estimator for linear elasticity should read
h_Q (\int_Q (f + div(\sigma(u)) : (f + div(\sigma(u)))^{1/2}

Best,
Rafa
