### ISSUE TITLE
Error Estimation (stress)

### ISSUE THREAD

**Issue by hamidratri** [rafavzqz/geopdes#13]
Dear Rafa
Thank you for your previous help.
As you mentioned  the estimator for linear elasticity should read
h_Q (\int_Q (f + div(\sigma(u)) : (f + div(\sigma(u)))^{1/2}
I think displacement field is the error estimator in above equation.
I would like to know how we can make one of the components of stress or von Mises stress as our error estimator? 

Best
Hamid

**Comment by rafavzqz** [comment]
Dear Hamid,
it seems we use a different nomenclature. For me, in the above equation the estimator is not the displacement. The estimator is the equation itself.

I'm not sure to understand what you mean by having the stress as the estimator. I suggest you to review the literature about a posteriori error estimators (the book by Ainsworth and Oden may be a good starting point), and try to find the one you want to implement. After that, we can discuss whether it is possible to do it in geopdes.

Best,
Rafa
