### ISSUE TITLE
shape functions hessian

### ISSUE THREAD

**Issue by hamidratri** [rafavzqz/geopdes#14]

**Comment by rafavzqz** [comment]
Dear Hamid,
you can find the expressions for the derivatives of the basis functions in the appendix of the PetIGA paper:
https://www.sciencedirect.com/science/article/pii/S0045782516303401

Honestly, I don't remember exactly how I wrote the function geopdes_inv_der2__, I should have the notes somewhere in my office, but I'm not sure I cand find them. In any case, the second derivatives of the inverse mapping are also written in the PetIGA paper.

Best,
Rafa
