### ISSUE TITLE
Scordelis-Lo roof problem

### ISSUE THREAD

**Issue by liuyuanhao** [rafavzqz/geopdes#15]
Dear Rafa,
Thank you for your previous help.
I would like to implement Scordelis-Lo roof problem related computation.I have read the documents in the appendix and GeoPDEs code libraries this week.However,my code level is very limited.
I feel a little embrassed ... Would you please give me a simple example like how to
compute Scordelis-Lo roof problem in isometric analysis with the GeoPDEs source code?If the GeoPDEs source code has the above function,please tell me about that.(Sry,I can't understand this code very well...)
Would you give me some guidance,please?

Deeply grateful,
Jim

**Comment by rafavzqz** [comment]
Dear Jim,
recently, Luca Coradello and Pablo Antolin added Kirchhoff-Love shells into GeoPDEs. The code is already in the public GitHub repository, and it will be part of the next release.

In the repository, you can find the example for the Scordelis-Lo roof in the file
ex_KL_shell_scordelis_lo_roof.m

Regards,
Rafa

**Comment by liuyuanhao** [comment]
Thank you so much! I have implemented it.

**Comment by liuyuanhao** [comment]
Dear Rafa,
Thank you for your previous help.I have a new problem. This program only calculates the value of the displacement at edge. Can we calculate the displacement at any point on the surface?

Deeply grateful,
Jim

**Comment by rafavzqz** [comment]
Dear Jim,
the function sp_eval can compute the solution (in your problem, the 
displacement) for any point. You need to give the parametric coordinates 
of the points, as in any other example of GeoPDEs.

If you only know the physical coordinates, and not the parametric ones, 
you can invert them using the function nrbinverse.

Regards,
Rafa

**Comment by Fate-seeker** [comment]
Dear Rafa,
I have encountered some difficulties and would like to ask you for advice. Although the GeoPDEs operation results give the coefficients before the basis function, how can I enter the command to get the function form of the solution, rather than the value at some points.

Deeply grateful,
Tom

**Comment by rafavzqz** [comment]
Dear Tom,
if I understood correctly, what you want is the explicit expression of 
your solution, as a combination of piecewise linear polynomials. That 
kind of command is not provided in GeoPDEs. You can try to check if 
there is something similar in the spline toolbox.

And if you want to compute it, my suggestion is that you apply 
refinement (with sp_refine, for instance) to write your solution in 
terms of C^0 splines in the same mesh. In this case all basis functions 
are mapped Bernstein polynomials, and the expression that you would get 
should be easier to handle.

Best regards,
Rafael
