### ISSUE TITLE
PHT splines

### ISSUE THREAD

**Issue by liuyuanhao** [rafavzqz/geopdes#16]
Hi Rafa,

Is there anything so far developed with PHT(polynomial spline over hierarchical t-meshes) spline based isogeometric analysis in GeoPDEs? If so then please kindly let me know. Thanks in advance and have a nice day.

Best regards,
Jim

**Comment by rafavzqz** [comment]
Dear Jim,
no, there is nothing implemented with PHT-splines so far, and I am not 
planning to do so. Have you checked if cubic HB-splines with C^1 
continuity give you the same space? I am not an expert on PHT-splines, 
so I have never checked it.

Best regards,
Rafa

**Comment by liuyuanhao** [comment]
Thank you so much!
