### ISSUE TITLE
Making stiffness matrix for solving quasi-linear problem

### ISSUE THREAD

**Issue by shreyachauhanto888** [rafavzqz/geopdes#20]
I am trying to solve the quasi-linear elliptic problem $-\nabla.(a(u))\nabla u=f\text{    in  }\Omega$, $u=0\text{  in  }\partial\Omega$, where $a(u)=1+u^2$. I am using Newton's method to solve this problem. In Newton's method while computing the Jacobian Matrix I need matrices $(a(u^k)\nabla u_i,\nabla v_j)$ and $(a'(u^k)\nabla u^ku_i,\nabla v_j)$, where $u^k$ is the initial guess for the iteration, $u_i$ and $v_j$ are basic functions. Here $u^k$ will be in vector form. So, how can I compute these matrices?

**Comment by rafavzqz** [comment]
Hi,
for the first matrix, you will need to define a new version of 
op_gradu_gradv_tp (in the class @sp_scalar), that takes as additional 
input the vector of degrees of freedom at the previous iteration, and 
computes the coefficient a(u^k) using this vector.

Inside the function, and inside the loop for the "columns", you should 
evaluate the solution in the quadrature nodes (using the function 
sp_eval_msh), which will give you an output of size [msh_col.nqn, 
msh_col.nel]. From the value of the function, you can compute a(u) as a 
vector of the same size, that would play the same role as "coeffs" in 
the current function.

For the second matrix, the idea is pretty much the same. In this case, 
the operator is quite similar top "op_vel_dot_gradu_v", which is used 
for advection terms. The coefficient in that function is the given 
advection velocity. In your case, it has to be replaced by $a'(u^k) 
\nabla u^k$. Again, this can be computed with the help of the function 
sp_eval_msh, which can also compute the gradient (see the help for the 
details).

There were discussions about similar questions in May 2016 and September 
2016, with Wilfred and Martina. You can try to check the archives of the 
geopdes-users mailing list for more details.

Best regards,
Rafa

**Comment by shreyachauhanto888** [comment]
Respected Sir,

Thank you very much for your help.

Regards,
Shreya
