### ISSUE TITLE
Mesh size in the physical domain

### ISSUE THREAD

**Issue by shreyachauhanto888** [rafavzqz/geopdes#21]
I am studying about the order of convergence in Isogeometric Method for the simple elliptic problem. We know that the size $h_K$ of an element $K$ in the physical mesh is related to the element size $h_Q$ of the element $Q$ in the parametric domain. My question is how can we find $h_K$ in GeoPDE ?

**Comment by rafavzqz** [comment]
Hi,
to study the order of convergence, you can use the mesh size in the 
parametric domain. This is what most people usually do (including 
myself), and it is fine as long as the parametrization does not have 
singularities.

If you still want to compute the real mesh size in the physical domain, 
there is no accurate way to do it. You can get an estimate if you 
compute the distance between opposite vertices of each element in the 
physical domain. A precise computation would require more complex 
methods, but I don't think it is worth to do it if you only want to 
study convergence in a standard case.

Best,
Rafa

**Comment by shreyachauhanto888** [comment]
Thank you very much for the response.

Regards,
Shreya Chauhan
