### ISSUE TITLE
[THB-splines] Constructing hierarchical spaces. 

### ISSUE THREAD

**Issue by qTipTip** [rafavzqz/geopdes#3]
Hi!

First and foremost, thanks for providing this package! 

I am currently working with truncated hierarchical B-splines, and I would like to assemble the mass matrix for a space corresponding to a grid of the following type:

![hierarchical_grid](https://user-images.githubusercontent.com/11932512/49148108-bf525f00-f306-11e8-9155-219454cc3e77.png)

However, I was wondering what the best way of constructing such a space using your package might be?
I've tried using the `build_hspace_from_cells` function, but this requires me to label each element individually, and for deep nesting this may be infeasable.

Do you happen to have any convenience-functionality lying around that I have missed, or is this something that is fairly easy to do in Octave/Matlab? My Octave/Matlab experience is limited.

Thanks in advance!

**Comment by rafavzqz** [comment]
Hi Ivar!

The package is meant to perform refinement adaptively, so it is not well designed to give a mesh manually. But in cases with a simple refinement pattern, as in your example, it is not so difficult to give the active cells manually, using some Octave/Matlab functionality (mainly sub2ind and ndgrid).

I will assume that you start with a mesh of NxN elements, and you want to refine the central KxK (N=10 and K=4 in you case). For simplicity, I also assume that both N and K are even. You can get the active cells like this.

for lev = 1:nlevels
 Nlev = N * 2^(lev-1);
 inds = (Nlev/2 - k/2):(Nlev/2 + k/2 + 1);
 [indx, indy] = ndgrid (inds, inds);
 marked_of_level = sub2ind ([Nlev, Nlev], indx, indy);
 cells{lev} = setdiff (1:Nlev^2, marked_of_level);
end

So, you identify the 1D indices of cells to be refined (inds), then use ndgrid and sub2ind to get the corresponding 2D indices (marked_of_level), and then setdiff to obtain the active cells, that is, the ones that you do not refine.

Best,
Rafa

**Comment by qTipTip** [comment]
Hi! Thank you for a detailed response!

I tried using your code-snippet for generating the cell-array of active cells for each level, and it did so correctly. However, when I pass this into the `build_hspace_from_cells` with `nlevels > 1` i obtain the following error:

```matlab
warning: called from
    mp_geo_read_nurbs at line 64 column 7
    mp_geo_load at line 116 column 50
    adaptivity_initialize_laplace at line 41 column 55
    build_hspace_from_cells at line 67 column 14
    mesh_construction_bug at line 15 column 6
error: hmsh0: subscripts must be either integers 1 to (2^31)-1 or logicals
error: called from
    hmsh_refine>update_active_cells at line 97 column 27
    hmsh_refine at line 41 column 20
    adaptivity_refine at line 46 column 17
    build_hspace_from_cells at line 77 column 18
    mesh_construction_bug at line 15 column 6
>>
```

That is, running the following script:
```matlab
clear all

N = 10;
k = 2;
nlevels = 2;
cells = {}
for lev = 1:nlevels
  Nlev = N * 2^(lev-1);
  inds = (Nlev/2 - k/2):(Nlev/2 + k/2 + 1);
  [indx, indy] = ndgrid (inds, inds);
  marked_of_level = sub2ind ([Nlev, Nlev], indx, indy);
  cells{lev} = setdiff (1:Nlev^2, marked_of_level);
end

[m, s] = build_hspace_from_cells(2, 3, N, cells, 'standard', true)
```

Am I missing something?

**Comment by rafavzqz** [comment]
That's an old bug in build_hspace_from_cells, that was considering as the input the marked cells instead of the active ones. Unfortunately, the hierarchical code is not in the public repository yet, but you can make things work either calling the funcion with 
cells{lev} = marked_of_level; 

or replacing line 75 of the function build_hspace_from_cells with the following:
marked{ref} = setdiff (hmsh.active{ref}, cells{ref});

**Comment by qTipTip** [comment]
Thank you so much! 
Replacing line 75 in `build_hspace_from_cells` did the trick! 
:+1:
