### ISSUE TITLE
Linear elasticity: numbering of the functions

### ISSUE THREAD

**Issue by didadidadada** [rafavzqz/geopdes#5]
Dear Rafa
I encounter a problem when I solved a linear elasticity problem with your GEOPDE package. The computed displacement of the load point is totally different from the result obtained from other distributed IGA package, e.g., igafem-nguyen. The problem setting and the corresponding boundary condition are as follows:

![image](https://user-images.githubusercontent.com/40538979/50323824-862c9980-0516-11e9-84b4-d15e19144a9b.png)

problem_data.geo_name = nrb4surf([0 0], [3 0], [0 1], [3 1]);

% Type of boundary conditions
problem_data.nmnn_sides   = [];
problem_data.press_sides  = [];
problem_data.drchlt_sides = [];
problem_data.symm_sides   = [];

% Physical parameters
E  =  1; nu = .3; 
problem_data.lambda_lame = @(x, y) ((nu*E)/((1+nu)*(1-2*nu)) * ones (size (x)));
problem_data.mu_lame = @(x, y) (E/(2*(1+nu)) * ones (size (x)));

% Source and boundary terms
problem_data.f = @(x, y, ind) zeros (2, size (x, 1), size (x, 2));
problem_data.h = @(x, y, ind) zeros (2, size (x, 1), size (x, 2));

% Exact solution (optional)
% uxex = @(x,y) sin(2*pi*x).*(sin(2*pi*y));
% uyex = @(x,y) sin(2*pi*x).*(sin(2*pi*y));
% problem_data.uex = @(x, y) cat(1, ...
%                 reshape (uxex (x,y), [1, size(x)]), ...
%                 reshape (uyex (x,y), [1, size(x)]));

% 2) CHOICE OF THE DISCRETIZATION PARAMETERS
clear method_data
method_data.degree     = [2 2];     % Degree of the bsplines
method_data.regularity = [1 1];     % Regularity of the splines
method_data.nsub       = [64 32];     % Number of subdivisions
method_data.nquad      = [3 3];     % Points for the Gaussian quadrature rule

The calculation process are changed into:
fixeddofs = [sp.boundary(1).dofs(1:2:end-1)  sp.boundary(3).dofs(end)];
int_dofs=setdiff(1:sp.ndof,fixeddofs);
loaddofs=sp.boundary(1).dofs(end);
rhs(loaddofs)=-1;
u(fixeddofs) =0;
% Solve the linear system
u(int_dofs) = mat(int_dofs, int_dofs) \ rhs(int_dofs);

The final cauculated results is u(loaddofs)=-2.8568 which is tollolly different from the result obtained by the package of igafem-nguyen where u(loaddofs)= -117.9371 under the same problem configuration.
Can you help me solve this problem?
Thank you very much!

**Comment by rafavzqz** [comment]
Dear didadidadada,
in GeoPDEs, the degrees of freedom of vector-valued spaces are not numbered following the nodes, but following the components. This is necessary for curl-conforming and div-conforming spaces, where the number of functions in each component is different.

You have to take this into account in the computation of fixeddofs, and you will get the expected result.
 fixeddofs = [sp.boundary(1).dofs(1:end/2) sp.boundary(3).dofs(end)];

By the way, plotting the solution like in the examples is also helpful to understand where the error comes from.

Best,
Rafa

**Comment by didadidadada** [comment]
Dear Rafa,
I am very grateful for your insightful guidance and advice! 

Best,
didadidadada
