### ISSUE TITLE
Draw THB basis

### ISSUE THREAD

**Issue by hamidratri** [rafavzqz/geopdes#7]
Dear Rafa
Thank you for your previous help.
I would like to know if it is possible to plot the THB basis functions with the GeoPDEs source code?
Of course, the hierarchical mesh can be drawn using _hmsh_plot_cells_ code, is there any way to draw the hierarchical space?

Best Regards
Hamid

**Comment by rafavzqz** [comment]
Dear Hamid,
probably the simplest way to do it, and to avoid implementing new code, is to plot basis functions as you do with the solution of your problem, setting all the degrees of freedom to zero except one. Something like this (2D case):

for ii = 1:hspace.ndof
  u = zeros (hspace.ndof, 1); u(ii) = 1;
  [eu,F] = sp_eval (u, hspace, geometry, npts);
  surf (squeeze(F(1,:,:)), squeeze(F(2,:,:)), eu);
  hold on
end

Best,
Rafa

**Comment by hamidratri** [comment]
Dear Rafa
Thank you for your guide.
I plan to write a new code like _hmsh_plot_cells_ for hierarchical space including one and two-dimensional cases.
Thanks again for your help.

Best,
Hamid

**Comment by hamidratri** [comment]
Dear Rafa
I appreciate the time you spend guiding me.
I am writing to ask if you could help me with how I can translate control points between different hierarchical levels?
suppose I have control points of level one, how can I calculate the control points of (T)HB space?

Best Regards
Hamid
