### ISSUE TITLE
Fichera Corner

### ISSUE THREAD

**Issue by hamidratri** [rafavzqz/geopdes#9]
Dear Rafa
Hi
First, thank you for the time you provide me.
I have solved Fichera corner example, and I could capture the singularity and the results for three steps of refinement are as follows
![Capture](https://user-images.githubusercontent.com/23305243/57950128-97c67180-78fb-11e9-90fa-f0f11ee94885.PNG)
Now I want to compare the results of the energy norm with GeoPDE, would you mind telling me how I should provide the input data? 
My input data is as follows

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% PHYSICAL DATA OF THE PROBLEM
clear problem_data  
% Physical domain, defined as NURBS map given in a text file
problem_data.geo_name = 'geo_fichera.txt';

% Type of boundary conditions for each side of the domain
problem_data.nmnn_sides   = [];
problem_data.drchlt_sides = 1;

% Physical parameters
problem_data.c_diff  = @(x, y, z) ones(size(x));
problem_data.grad_c_diff = @(x, y, z) cat (1, ...
            reshape (zeros(size(x)), [1, size(x)]), ...
            reshape (zeros(size(x)), [1, size(x)]), ...
            reshape (zeros(size(x)), [1, size(x)]));

% Source and boundary terms

radius                = @(x,y,z) (x.^2 + y.^2 + z.^2);
uex                    = @(x,y,z) (radius(x,y,z)).^(1/4);
problem_data.f  = @(x,y,z) ((-3/4)*radius(x,y,z)).^(-3/4);
problem_data.h = @(x,y,z,ind) uex(x,y,z);

% Exact solution (optional)
problem_data.uex     = uex;
problem_data.graduex = @(x, y, z) cat (1, ...
            reshape (x./(2*(x.^2 + y.^2 + z.^2).^(3/4)), [1, size(x)]), ...
            reshape (y./(2*(x.^2 + y.^2 + z.^2).^(3/4)), [1, size(x)]), ...
            reshape (z./(2*(x.^2 + y.^2 + z.^2).^(3/4)), [1, size(x)]));

% CHOICE OF THE DISCRETIZATION PARAMETERS (Coarse mesh)
clear method_data
method_data.degree             = [2 2 2];      % Degree of the splines
method_data.regularity         = [1 1 1];      % Regularity of the splines
method_data.nsub_coarse     = [2 2 2];      % Number of subdivisions of the coarsest mesh
method_data.nsub_refine      = [2 2 2];      % Number of subdivisions for each refinement
method_data.nquad              = [3 3 3];      % Points for the Gaussian quadrature rule
method_data.space_type       = 'standard';   % 'simplified' (only children functions) or 'standard' 
method_data.truncated         = 1;            % 0: False, 1: True

% ADAPTIVITY PARAMETERS
clear adaptivity_data
adaptivity_data.flag                  = 'elements';
% adaptivity_data.flag              = 'functions';
adaptivity_data.C0_est             = 1.0;
adaptivity_data.mark_param    = .5;
adaptivity_data.mark_strategy = 'MS';
adaptivity_data.max_level        = 10;
adaptivity_data.max_ndof        = 5000;
adaptivity_data.num_max_iter  = 5;
adaptivity_data.max_nel           = 5000;
adaptivity_data.tol                    = 1e-5;
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

Best regards
Hamid

**Comment by hamidratri** [comment]
Dear Rafa
Hi again

I used the GeoPDE and got the following results which are not satisfactory:
%%%%%%%%%%%%%%%%%% Iteration 4 %%%%%%%%%%%%%%%%%%
SOLVE:
Number of elements: 203. Total DOFs: 391 
ESTIMATE:
Computed error estimator: 0.884463 
Error in L2 norm     = 0.0486526
Error in H1 norm     = 0.172881
Error in H1 seminorm = 0.165894
MARK:
7 elements marked for refinement 
REFINE:

%%%%%%%%%%%%%%%%%% Iteration 5 %%%%%%%%%%%%%%%%%%
SOLVE:
Number of elements: 252. Total DOFs: 416 
ESTIMATE:
Computed error estimator: 0.777571 
Error in L2 norm     = 0.0486276
Error in H1 norm     = 0.172739
Error in H1 seminorm = 0.165753
Warning: reached the maximum number of iterations
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
But the results by running my own code are totally different, e.g., for L2 norm my results are

Degrees of freedom | L2 error
-- | --
646 | 0.00797943
2055 | 0.00328664
6262 | 0.00137455
17252 | 0.00076550



Can you tell me what's the problem?

Best
Hamid

**Comment by rafavzqz** [comment]
Dear Hamid,
I think you have already fixed the issue of imposing the boundary conditions. 

From my own experience, when you don't get convergence the error is usually in the input data. I suggest you to consider the tensor-product (multipatch) case, instead of the hierarchical basis, and check the convergence with uniform refinement.

Best,
Rafa
